version: '2'
services:
  kafka:
    image: landoop/fast-data-dev:2.0
    ports:
      - 2181:2181           # zk
      - 3030:3030           # landloop ui
      - 8081-8083:8081-8083 # rest proxy, schema registry, kafka connect
      - 9092:9092           # kafka broker
    environment:
      ADV_HOST: 127.0.0.1
      SAMPLEDATA: 0
      RUNNING_SAMPLEDATA: 1
      RUNTESTS: 0
      FORWARDLOGS: 0
      DISABLE_JMX: 1
      BROWSECONFIGS: 1
